#ifndef __GUGUMIPS_NSCSCC_CONFIG_H
#define __GUGUMIPS_NSCSCC_CONFIG_H

#define CONFIG_SKIP_LOWLEVEL_INIT
#define CONFIG_SYS_MIPS_TIMER_FREQ 50000000
#define CONFIG_SYS_SDRAM_BASE 0x80000000
#define CONFIG_SYS_SDRAM_SIZE 0x8000000 /* 128 Mbytes */
#define CONFIG_SYS_INIT_SP_ADDR                                                \
  (CONFIG_SYS_SDRAM_BASE + CONFIG_SYS_SDRAM_SIZE - 0x1000)
#define CONFIG_SYS_MALLOC_LEN (256 << 10)
#define CONFIG_SYS_MONITOR_BASE CONFIG_SYS_TEXT_BASE
#define CONFIG_SYS_LOAD_ADDR 0x80000000 /* default load address */
#define CONFIG_SYS_CBSIZE 1024
#define CONFIG_SYS_MAXARGS 16
#define CONFIG_SYS_MAX_FLASH_BANKS 0

#define CONFIG_ENV_IS_NOWHERE 1
#define CONFIG_ENV_SIZE 0x1000

#define CONFIG_TIMESTAMP /* Print image info with timestamp */

#define DEBUG
/* UltraEmbedded USB1.1 Core Debug */
#define UE11_DEBUG
#define UE11_INFO

#endif /* __GUGUMIPS_NSCSCC_CONFIG_H */
